### DISCUSSION TITLE
CSS Color Collector

### DISCUSSION THREAD

**Discussion by xkeshav** [microsoft/vscode-discussions#442] [Extension Show and Tell]
developed an exetenion which works on css file, it does

- scan css file and collect all colors ( whether named color, rgb or hex or any other format) written in file
- turn color into variable name which contains property and selector information in it 
-  replace color code with these variable
-  add :root on top of css file which have all variable and 

for eg

```css
body {
  background-color: #285; 
}
```

will change the file into

```css
:root {
--body--bg-1: #285;
}

body {
  background-color: var(--body-bg-1);
}

```

here is the gif

![collector](https://user-images.githubusercontent.com/415219/216803693-5e7a5c58-c34c-4149-b281-6e676f877061.gif)

and here is the repo link: https://github.com/xkeshav/color-collector/tree/develop

Kindly have a look and suggest what can be modified here. 

PS. test case writing is in progress :)

Thanks.
